version: 1.0.{build}
image: Visual Studio 2019

install:
  - choco install mingw -y
  - refreshenv
  - set PATH=%PATH%;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin


build_script:
  - gcc --version
  - gcc -O2 -Wall *.c -o microsocks.exe

artifacts:
  - path: microsocks.exe
    name: microsocks
