image: Visual Studio 2022

install:
  - choco install -y msys2
  - set PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\mingw64\bin;%PATH%
  - C:\tools\msys64\usr\bin\bash -lc "pacman -Sy --noconfirm mingw-w64-x86_64-gcc"

build_script:
  - git clone https://github.com/rofl0r/microsocks.git
  - bash -lc "cd \$(cygpath \"${APPVEYOR_BUILD_FOLDER}/microsocks\") && gcc -O2 -Wall socks.c microsocks.c utils.c -lws2_32 -o microsocks.exe"

artifacts:
  - path: microsocks\microsocks.exe
    name: microsocks-exe
