version: 1.0.{build}
image: Visual Studio 2019

install:
  - choco install mingw -y
  - set PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%

build_script:
  - gcc -O2 -Wall microsocks.c -o microsocks.exe

artifacts:
  - path: microsocks.exe
    name: microsocks
