image: Visual Studio 2022

install:
  - choco install -y msys2
  - refreshenv
  - set PATH=%PATH%;C:\tools\msys64\usr\bin

build_script:
  - git clone https://github.com/rofl0r/microsocks.git
  - cd microsocks
  - bash -lc "gcc -O2 -Wall *.c -static -lws2_32 -o microsocks.exe"

artifacts:
  - path: microsocks\microsocks.exe
    name: microsocks-exe
